apiVersion: batch/v1
kind: Job
metadata:
  name: openms-pipeline-k8s-job
spec:
  activeDeadlineSeconds: 100
  template:
    metadata:
      name: openms-pipeline-k8s
    spec:
      containers:
      - name: openms-pipeline-k8s-container
        image: "farmbio/scipipe"
        command: ["sh", "-c", "cd $GOPATH/src/github.com/scipipe/scipipe; git pull; cd -; go run k8s_openms.go"]
        volumeMounts:
        - mountPath: "/scipipe-data"
          name: scipipe-volume
          readOnly: false
      restartPolicy: Never
      volumes:
      - name: scipipe-volume
        hostPath:
          path: "/scipipe-data"
